# These options apply to how the script will operate.
script_options:
  # Switch between testnet and mainnet
  # Setting this to False will use REAL funds, use at your own risk
  # I don't advice to change TEST_MODE while the bot is running. I haven't tested what it does
  # when the bot changes from test mode to use real money all of a sudden or vice versa
  TEST_MODE: True
  LOG_TRADES: True
  LOG_FILE: 'trades.txt'
  DEBUG: False

  # Set this to true if you are accessing binance from within the United States of America
  # Need to change TLD
  AMERICAN_USER: False


# These options apply to the trading methods the script executes
trading_options:

  # select your base currency to use for trading (trade for example USDT pairs)
  PAIR_WITH: USDT

  # Total amount per trade (your base currency balance must be at least MAX_COINS * QUANTITY)
  # Binance uses a minimum of 10 USDT per trade, add a bit extra to enable selling if the price drops.
  # Recommended: no less than 12 USDT. Suggested: 15 or more.
  QUANTITY: 250

  # List of trading pairs to exclude
  # by default we're excluding the most popular fiat pairs
  FIATS:
    - EURUSDT
    - GBPUSDT
    - JPYUSDT
    - USDUSDT
    - DOWN
    - UP

  # Name of custom tickers list
  #TICKERS_LIST: 'tickers.txt'
  TICKERS_LIST: 'tickers_all_USDT.txt'

   # Maximum number of coints to hold
   # Set this to zero if you want the bot to sell all the(possibly losing at the moment) coins at TP.
   # If you want to avoid losses, then set your STOP_LOSS high enough
   # Set this to -1 if you want the bot to terminate automatically when all the coins are sold
  MAX_COINS: 18

  # the amount of time in MINUTES to calculate the difference from the current price
  TIME_DIFFERENCE: 1

  # Numer of times to check for TP/SL during each TIME_DIFFERENCE Minimum 1
  RECHECK_INTERVAL: 6

  # the difference in % between the first and second checks for the price.
  CHANGE_IN_PRICE: 90

  # define in % when to sell a coin that's not making a profit, this has to be NEGATIVE number
  STOP_LOSS: -90

  # define in % when to take profit on a profitable coin
  TAKE_PROFIT: 1.0

  # Use custom tickers.txt list for filtering pairs
  CUSTOM_LIST: True

  # whether to use trailing stop loss or not; default is True
  USE_TRAILING_STOP_LOSS: True

  # when hit TAKE_PROFIT, move STOP_LOSS to TRAILING_STOP_LOSS percentage points below TAKE_PROFIT hence locking in profit
  # when hit TAKE_PROFIT, move TAKE_PROFIT up by TRAILING_TAKE_PROFIT percentage points
  # TRAILING_STOP_LOSS should be be greater than TRAILING_TAKE_PROFIT
  TRAILING_STOP_LOSS: 0.2
  TRAILING_TAKE_PROFIT: 0.1

  # EX_PAIRS is a list of fiat currencies and margin symbols that I am excluding.
  # Anything added here will be excluded from coin withdrawal and will not be sold.
  EX_PAIRS: ['EUR', 'USD', 'GBP', 'BUSD', 'USDT', 'AUD', 'BRL', 'RUB', 'TRY', 'USDC', 'PAX', 'BIDR', 'DAI', 'IDRT',
  'UAH', 'NGN', 'VAI', 'BVND', 'JPY', 'NCASH', 'UPUSDT', 'DOWNUSDT', 'USDTUP', 'USDTDOWN', 'BNBDOWN',
  'EOSDOWN', 'XLMDOWN', 'UNIDOWN', 'LINKDOWN', 'FILDOWN', 'TRXDOWN', 'XRPDOWN', 'AAVEDOWN', 'SUSHIDOWN',
  'XTZDOWN', 'ADADOWN', '1INCHDOWN', 'BTCDOWN', 'SXPDOWN', 'DOTDOWN', 'ETHDOWN', 'BCHDOWN', 'LTCDOWN',
  'YFIDOWN', 'XTZUP', 'DOTUP', 'ADAUP', 'SUPER', 'AAVEUP', 'BTCUP', 'BNBUP', 'SXPUP', 'YFIUP', 'XLMUP',
  'UNIUP', 'FILUP', '1INCHUP', 'LINKUP', 'LTCUP', 'ETHUP', 'SUSHIUP', 'EOSUP', 'XRPUP', 'TRXUP', 'BCHUP',
  'RENBTC', 'B' ]

  # Trading fee in % per trade.
  # If using 0.075% (using BNB for fees) you must have BNB in your account to cover trading fees.
  # If using BNB for fees, it MUST be enabled in your Binance 'Dashboard' page (checkbox).
  TRADING_FEE: 0.075

  SIGNALLING_MODULES:
    - pausebotmod
    - VolScan
  #  - signalsamplemod
  #  - custsignalmod
  #  - os_pausebot_MAv2
  #  - djcommie_signalsell_rsi_stoch
  #  - djcommie_signalbuy_rsi_stoch
